# Generated by Django 3.2.9 on 2021-12-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_refferalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='refferal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
